version: '3.7'

services:
    next:
        build: .
        image: zet:latest
        container_name: zet
        restart: unless-stopped
        networks:
            - proxy

networks:
    proxy:
        external:
            name: reverse_proxy
